# Generated by Django 4.2.4 on 2023-12-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_bodytype_make_remove_model_image_alter_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodytype',
            name='image',
            field=models.ImageField(upload_to='media/images/body'),
        ),
        migrations.AlterField(
            model_name='make',
            name='image',
            field=models.ImageField(upload_to='media/images/make'),
        ),
    ]
