# Generated by Django 4.2.4 on 2023-12-24 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_bodytype_image_alter_make_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('locationValue', models.CharField(max_length=2400)),
                ('yearOfManufacture', models.CharField(max_length=20)),
                ('isFeatured', models.BooleanField()),
                ('isAvailable', models.BooleanField()),
                ('transmission', models.CharField(max_length=50)),
                ('horsePower', models.IntegerField()),
                ('acceleration', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fuelType', models.CharField(max_length=50)),
                ('body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.bodytype')),
                ('make', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.make')),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='make',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.make'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='media/images/cars')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.car')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.model'),
        ),
    ]
