# Generated by Django 4.2.4 on 2023-12-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_car_model_make_image_car_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='drive',
            field=models.CharField(default='2WD', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='engineSize',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=50000),
        ),
    ]
